#!/bin/bash

modulename='Net::LDAP::SimpleServer'
modulepath=$(echo $modulename | sed -e 's/::/\//g').pm
moduledash=$(echo $modulename | sed -e 's/::/-/g')

dry_run=1
[ "$1" = "-f" ] && dry_run=0

is_dry_run() {
  [[ "${dry_run}" -eq 1 ]]
}

msg() {
  echo "$@" >&2
}

msg "== Checking current directory"
[ -f ./lib/${modulepath} ] || {
    msg "**** Cannot find ./lib/${modulepath}"
    exit 1
}

is_dry_run && {
    msg "***** DRY-RUN: use -f to actually commit! *****"
}

msg "== Running ./Build.PL"
perl ./Build.PL || exit 1

msg "== Running tests"
./Build disttest || exit 1

msg "== Running through perltidy"
{
    find lib/ -name '*.pm' | xargs perltidy -b \
    && find t/ -name '*.t' | xargs perltidy -b
} || {
    msg "**** Failed syntax check! Aborting."
    exit 1
}

msg "== Adding module to git"
is_dry_run || git add lib/${modulepath}

msg "== Making README"
( readme=../README
  is_dry_run && readme=/dev/null 
  cd lib; perldoc -t -F ${modulepath} > ${readme} ) \
  || exit 1
is_dry_run || git add README

msg "== Creating META.yml"
./Build distmeta || exit 1

version=$(perl -nle 'if( /^version/ ) { s/^\S+\s+v//; print; }' META.yml)
msg "== Version: ${version}"

msg "== Generating <Changes> automagically"
grep -q "^${version}" Changes && {
  msg "**** VERSION ${version} is already in Changes. Aborting..."
  exit 1
}
changes=Changes
is_dry_run && changes=/dev/tty
cp Changes __changes && {
    echo "Revision history for ${moduledash}"
    echo ""
    printf '%-7s %s %s\n' "${version}" "$(date +%d.%m.%Y)" \
        "${modulename} DIST VERSION ${version}"
    perl -e 'print "="x7 . " " . "="x70 . "\n"'
    git log --oneline | perl -nle 'exit if /DIST VERSION/; print "$_";' &&
    echo "" &&
    cat __changes | perl -e '$a=<>; $a=<>; while(<>) { print }'
} > ${changes} \
  || exit 1
is_dry_run || {
  head -20 Changes
  git add Changes
}

msg "== Committing files to git"
is_dry_run || git commit -m "DIST VERSION ${version}" || exit 1

msg "== Tagging as v${version}"
is_dry_run || git tag v${version} HEAD || exit 1

msg "== Making distribution package"
./Build dist || exit 1

d=$(echo ${moduledash}*.tar.gz) 
msg "== Moving file $d to home directory"
is_dry_run || mv $d ${HOME}

msg "== Cleaning directory"
is_dry_run || git clean -fd

is_dry_run && {
    msg "***** DRY-RUN: use -f to actually commit! *****"
}

